In [2]:
import numpy as np
import pandas as pd
import seaborn as sns 
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

In [3]:
df = pd.read_csv('data.csv').drop(['Unnamed: 0'],axis=1)
df

,0,1,2,3,4,5,6,7,8,9,...,207,208,209,210,211,212,213,214,215,216
0,R,683.019479,99.231824,247.039406,298.075093,688.824307,1860.992613,943.568497,516.094460,122.585731,...,281.052519,818.911753,382.550333,101.372176,283.965835,1140.504149,1031.947240,202.345836,306.772137,258.378540
1,E,581.014867,42.237868,27.232563,167.140603,717.442925,822.680572,1493.455057,2540.961638,247.847485,...,127.287338,1118.748384,570.416737,458.359849,428.788421,1055.053815,934.872716,194.077932,410.678715,485.266592
2,N,203.514626,230.842533,103.519050,304.783775,2352.846155,2555.057291,1490.446267,393.913342,142.494226,...,321.669202,677.101174,831.442528,770.571002,447.723705,528.403393,700.020574,384.291699,355.883730,161.600511
3,I,1122.759329,468.060104,196.375193,174.441816,249.325393,714.823548,3220.575352,1776.119555,370.840793,...,638.538935,503.928457,245.577235,374.161266,501.263297,1598.038718,2566.025719,833.828486,61.987862,66.208259
4,N,548.379979,179.645430,288.780948,210.057796,1330.865989,2061.968305,808.251805,191.050595,184.094886,...,653.677418,345.578166,316.728525,196.248235,13.524524,494.775191,462.939055,138.800052,17.973648,127.394224
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47995,L,110.829279,25.934754,7.261765,463.464600,2166.044618,3737.335099,1260.830120,226.572095,0.000000,...,402.355506,586.758009,334.100672,179.565656,115.660182,600.927713,784.306757,299.815989,178.456857,457.391963
47996,T,424.395443,140.573745,46.681771,152.748387,379.072959,390.081085,248.137672,433.211783,393.627344,...,323.138946,151.320190,49.517176,177.937915,188.536906,320.544611,176.674816,294.987421,12.715458,48.200863
47997,F,297.314914,283.647120,105.903654,230.274294,367.616497,446.875940,182.294844,190.249639,194.571256,...,398.421446,929.176637,521.375687,572.918817,345.464999,832.510361,1047.229049,318.154450,447.396712,646.873134
47998,D,1021.463961,588.338554,588.432757,298.759615,450.108200,444.528540,364.162386,514.916892,286.330098,...,380.230553,550.274821,494.659081,457.802029,177.676283,785.109270,737.153482,186.139922,220.908482,459.211445
47999,V,1108.590249,515.432001,698.859563,800.724059,1177.497381,1342.819371,375.354706,301.654734,715.112546,...,58.737100,66.143548,0.000000,8.193248,58.893471,90.486672,90.617278,47.759878,0.000000,2.864926

In [4]:
X = df.drop(['0'],axis=1).values
y = df['0'].values

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, y, test_size=0.3, random_state=0)
print("X_train shape ",X_train.shape)
print("y_train shape ",Y_train.shape)
print("X_test shape ",X_test.shape)
print("Y_test shape ",Y_test.shape)

X_train shape  (33600, 216)
y_train shape  (33600,)
X_test shape  (14400, 216)
Y_test shape  (14400,)

In [12]:
from sklearn.svm import SVC
from sklearn.svm import LinearSVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier

#c1 = LogisticRegression()
c2 = LinearSVC(C=1, random_state=0)
#c2 = SVC(kernel = 'rbf', random_state = 1, C = 1, gamma = 0.1)
c3 = KNeighborsClassifier(n_neighbors=10, metric='minkowski', p=1)
#c4 = XGBClassifier(max_depth=2, learning_rate=0.05, n_estimators=250, objective='binary:logistic', random_state=1)
c5 = RandomForestClassifier(n_estimators=150, criterion='entropy', random_state = 0, max_depth=3)
c6 = DecisionTreeClassifier(criterion='entropy', random_state = 10, max_depth=7)

In [7]:
for c, label in zip([c2,c3, c5, c6],['SVM','KNN', 'Random forest', 'Decision tree']):
    c.fit(X_train,Y_train)
    y_train_pred = c.predict(X_train)
    y_test_pred = c.predict(X_test)
    kfold = KFold(n_splits = 20, shuffle=True, random_state = 10)
    modelo = c
    resultado = cross_val_score(modelo, X_train, Y_train, cv = kfold)

    print(label)
    print("Accuracy: %0.4f  [%s]" % (accuracy_score(Y_train,y_train_pred), 'Train set accuracy '))
    print("Accuracy: %0.4f  [%s]" % (accuracy_score(Y_test,y_test_pred), 'Test set accuracy '))
    print("Cross validation: %.2f%%" % (resultado.mean() * 100.0))
    print('\n')

SyntaxError: invalid character '̣' (U+0323) (3211479462.py, line 1)

In [13]:
for c, label in zip([c6],['Decision tree']):
    c.fit(X_train,Y_train)
    y_train_pred = c.predict(X_train)
    y_test_pred = c.predict(X_test)
    kfold = KFold(n_splits = 5, shuffle=True, random_state = 10)
    modelo = c
    resultado = cross_val_score(modelo, X_train, Y_train, cv = kfold)

    print(label)
    print("Accuracy: %0.4f  [%s]" % (accuracy_score(Y_train,y_train_pred), 'Train set accuracy '))
    print("Accuracy: %0.4f  [%s]" % (accuracy_score(Y_test,y_test_pred), 'Test set accuracy '))
    print("Cross validation: %.2f%%" % (resultado.mean() * 100.0))
    print('\n')

Decision tree
Accuracy: 0.3947  [Train set accuracy ]
Accuracy: 0.3708  [Test set accuracy ]
Cross validation: 37.19%